### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by pTinosq** [KAIKAKU-AI/perrito-ws#4]
We claim to be "made for developers by developers" and proceed to only have light mode (even though there's a theme toggle). This is **CRIMINAL**.

Dark mode pls

**Comment by IvanKAIKAKU** [comment]
Dark mode plz

**Comment by pTinosq** [comment]
> Dark mode plz

Working on it pal

**Comment by pTinosq** [comment]
Implemented dark mode in v0.8.6
